"""
PPT Generator MCP Server
Provides PowerPoint creation tools via FastMCP.
Maintains an internal Presentation object across tool calls.
"""

import os
import logging
from pathlib import Path
from typing import List

from fastmcp import FastMCP
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="[PPT-MCP] %(asctime)s %(levelname)s │ %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("ppt_mcp")

# ── Server ─────────────────────────────────────────────────────────────────────
mcp = FastMCP(
    name="ppt-generator-mcp",
)

# ── Internal state (persists across tool calls within same process) ─────────────
_state: dict = {
    "presentation": None,   # pptx.Presentation object
    "filename": None,        # intended save path
    "slide_count": 0,
}

# ── Colour palette (Midnight Executive theme) ──────────────────────────────────
DARK_BG    = RGBColor(0x1E, 0x27, 0x61)   # #1E2761 deep navy
LIGHT_BG   = RGBColor(0xF0, 0xF4, 0xFF)   # #F0F4FF ice-blue tint
TITLE_CLR  = RGBColor(0xFF, 0xFF, 0xFF)   # white   (on dark slides)
BODY_CLR   = RGBColor(0x1E, 0x27, 0x61)   # navy    (on light slides)
ACCENT     = RGBColor(0x4A, 0x90, 0xD9)   # sky-blue accent
BULLET_CLR = RGBColor(0x2C, 0x3E, 0x80)   # mid-navy for bullets

SLIDE_W = Inches(13.33)
SLIDE_H = Inches(7.5)


def _solid_bg(slide, colour: RGBColor) -> None:
    """Fill slide background with a solid colour."""
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = colour


def _add_text_box(
    slide,
    left: float,
    top: float,
    width: float,
    height: float,
    text: str,
    font_size: int,
    bold: bool,
    colour: RGBColor,
    align=PP_ALIGN.LEFT,
    italic: bool = False,
) -> None:
    """Helper: add a positioned text box to a slide."""
    txBox = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height)
    )
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = colour


def _build_title_slide(prs: Presentation, title: str) -> None:
    """Create a dark full-bleed title slide (slide 0)."""
    blank_layout = prs.slide_layouts[6]          # completely blank layout
    slide = prs.slides.add_slide(blank_layout)
    _solid_bg(slide, DARK_BG)

    # Decorative accent bar (left edge)
    bar = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        Inches(0), Inches(2.8), Inches(0.12), Inches(1.9),
    )
    bar.fill.solid()
    bar.fill.fore_color.rgb = ACCENT
    bar.line.fill.background()

    # Main title
    _add_text_box(
        slide,
        left=0.4, top=2.5, width=12.5, height=1.5,
        text=title,
        font_size=44, bold=True,
        colour=TITLE_CLR,
        align=PP_ALIGN.LEFT,
    )

    # Sub-label
    _add_text_box(
        slide,
        left=0.4, top=4.2, width=9, height=0.6,
        text="Auto-Generated by PPT Agent",
        font_size=16, bold=False, italic=True,
        colour=ACCENT,
        align=PP_ALIGN.LEFT,
    )

    log.info("Built title slide: %s", title)


def _build_content_slide(
    prs: Presentation, title: str, bullets: List[str], slide_num: int
) -> None:
    """
    Add a content slide with:
    - Light background
    - Coloured header bar
    - Title text
    - 3-5 bullet points with decorative markers
    - Slide number footer
    """
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _solid_bg(slide, LIGHT_BG)

    # Header band
    header = slide.shapes.add_shape(
        1, Inches(0), Inches(0), Inches(13.33), Inches(1.4)
    )
    header.fill.solid()
    header.fill.fore_color.rgb = DARK_BG
    header.line.fill.background()

    # Title in header band
    _add_text_box(
        slide,
        left=0.35, top=0.2, width=12.5, height=1.0,
        text=title,
        font_size=32, bold=True,
        colour=TITLE_CLR,
        align=PP_ALIGN.LEFT,
    )

    # Left accent stripe (content area)
    stripe = slide.shapes.add_shape(
        1, Inches(0.35), Inches(1.55), Inches(0.06), Inches(5.5)
    )
    stripe.fill.solid()
    stripe.fill.fore_color.rgb = ACCENT
    stripe.line.fill.background()

    # Bullet points
    bullet_top = 1.65
    bullet_spacing = min(0.95, (5.6 / max(len(bullets), 1)))

    for i, bp in enumerate(bullets[:5]):
        # Bullet circle marker
        dot = slide.shapes.add_shape(
            9,  # oval
            Inches(0.55), Inches(bullet_top + i * bullet_spacing + 0.12),
            Inches(0.22), Inches(0.22),
        )
        dot.fill.solid()
        dot.fill.fore_color.rgb = ACCENT
        dot.line.fill.background()

        # Bullet text
        _add_text_box(
            slide,
            left=0.9, top=bullet_top + i * bullet_spacing,
            width=12.0, height=bullet_spacing,
            text=bp,
            font_size=18, bold=False,
            colour=BODY_CLR,
            align=PP_ALIGN.LEFT,
        )

    # Slide number badge (bottom-right)
    badge = slide.shapes.add_shape(
        9, Inches(12.3), Inches(7.0), Inches(0.7), Inches(0.35)
    )
    badge.fill.solid()
    badge.fill.fore_color.rgb = DARK_BG
    badge.line.fill.background()

    _add_text_box(
        slide,
        left=12.3, top=7.0, width=0.7, height=0.35,
        text=str(slide_num),
        font_size=11, bold=True,
        colour=TITLE_CLR,
        align=PP_ALIGN.CENTER,
    )

    log.info("Built content slide #%d: %s (%d bullets)", slide_num, title, len(bullets))


# ── MCP Tools ──────────────────────────────────────────────────────────────────

@mcp.tool()
def create_presentation(filename: str) -> str:
    """
    Initialise a new PowerPoint presentation with *filename* as the save path.
    Resets any previously open presentation.
    """
    global _state
    prs = Presentation()
    prs.slide_width  = SLIDE_W
    prs.slide_height = SLIDE_H

    _state["presentation"] = prs
    _state["filename"]     = filename
    _state["slide_count"]  = 0

    log.info("create_presentation → %s", filename)
    return f"Presentation initialised. Will save to: {filename}"


@mcp.tool()
def add_slide(title: str, bullet_points: List[str]) -> str:
    """
    Add one slide to the current presentation.

    Args:
        title:         Slide heading (string).
        bullet_points: List of 3-5 bullet point strings.

    Returns a confirmation string.
    """
    prs = _state.get("presentation")
    if prs is None:
        return "ERROR: No presentation open. Call create_presentation first."

    # Enforce 3-5 bullet points
    if len(bullet_points) < 3:
        # Pad with generic bullets so we never crash
        while len(bullet_points) < 3:
            bullet_points.append("Additional detail to be expanded upon.")
    bullet_points = bullet_points[:5]

    _state["slide_count"] += 1
    count = _state["slide_count"]

    if count == 1:
        # First call → produce the special title slide
        _build_title_slide(prs, title)
    else:
        _build_content_slide(prs, title, bullet_points, count - 1)

    return (
        f"Slide {count} added: '{title}' "
        f"with {len(bullet_points)} bullet(s). "
        f"Total slides so far: {count}."
    )


@mcp.tool()
def save_presentation() -> str:
    """
    Save the current presentation to the filename given in create_presentation.
    Returns the full path of the saved file.
    """
    prs      = _state.get("presentation")
    filename = _state.get("filename")

    if prs is None:
        return "ERROR: No presentation open."
    if not filename:
        return "ERROR: No filename set. Call create_presentation first."

    save_path = Path(os.getcwd()) / filename
    prs.save(str(save_path))
    log.info("save_presentation → %s  (%d slides)", save_path, _state["slide_count"])
    return (
        f"Presentation saved: {save_path}  "
        f"({_state['slide_count']} slides)"
    )


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    log.info("Starting PPT Generator MCP Server …")
    mcp.run(transport="stdio")
